
export const LOCAL_LOCATIONS = [
  // Quận/Huyện Hà Nội (Đã lược bỏ nhãn)
  { name: "Ba Đình, Hà Nội", shortName: "Ba Đình" },
  { name: "Hoàn Kiếm, Hà Nội", shortName: "Hoàn Kiếm" },
  { name: "Tây Hồ, Hà Nội", shortName: "Tây Hồ" },
  { name: "Long Biên, Hà Nội", shortName: "Long Biên" },
  { name: "Cầu Giấy, Hà Nội", shortName: "Cầu Giấy" },
  { name: "Đống Đa, Hà Nội", shortName: "Đống Đa" },
  { name: "Hai Bà Trưng, Hà Nội", shortName: "Hai Bà Trưng" },
  { name: "Hoàng Mai, Hà Nội", shortName: "Hoàng Mai" },
  { name: "Thanh Xuân, Hà Nội", shortName: "Thanh Xuân" },
  { name: "Sóc Sơn, Hà Nội", shortName: "Sóc Sơn" },
  { name: "Đông Anh, Hà Nội", shortName: "Đông Anh" },
  { name: "Gia Lâm, Hà Nội", shortName: "Gia Lâm" },
  { name: "Nam Từ Liêm, Hà Nội", shortName: "Nam Từ Liêm" },
  { name: "Bắc Từ Liêm, Hà Nội", shortName: "Bắc Từ Liêm" },
  { name: "Thanh Trì, Hà Nội", shortName: "Thanh Trì" },
  { name: "Mê Linh, Hà Nội", shortName: "Mê Linh" },
  { name: "Hà Đông, Hà Nội", shortName: "Hà Đông" },
  { name: "Sơn Tây, Hà Nội", shortName: "Sơn Tây" },
  { name: "Ba Vì, Hà Nội", shortName: "Ba Vì" },
  { name: "Phúc Thọ, Hà Nội", shortName: "Phúc Thọ" },
  { name: "Đan Phượng, Hà Nội", shortName: "Đan Phượng" },
  { name: "Hoài Đức, Hà Nội", shortName: "Hoài Đức" },
  { name: "Quốc Oai, Hà Nội", shortName: "Quốc Oai" },
  { name: "Thạch Thất, Hà Nội", shortName: "Thạch Thất" },
  { name: "Chương Mỹ, Hà Nội", shortName: "Chương Mỹ" },
  { name: "Thanh Oai, Hà Nội", shortName: "Thanh Oai" },
  { name: "Thường Tín, Hà Nội", shortName: "Thường Tín" },
  { name: "Phú Xuyên, Hà Nội", shortName: "Phú Xuyên" },
  { name: "Ứng Hòa, Hà Nội", shortName: "Ứng Hòa" },
  { name: "Mỹ Đức, Hà Nội", shortName: "Mỹ Đức" },

  // Giao Thủy, Nam Định (Mới)
  { name: "Giao Thủy, Nam Định", shortName: "Giao Thủy" },

  // Xã/Thị trấn Huyện Giao Thủy, Nam Định (Đã lược bỏ nhãn)
  { name: "Ngô Đồng, Giao Thủy, Nam Định", shortName: "Ngô Đồng" },
  { name: "Quất Lâm, Giao Thủy, Nam Định", shortName: "Quất Lâm" },
  { name: "Giao An, Giao Thủy, Nam Định", shortName: "Giao An" },
  { name: "Giao Châu, Giao Thủy, Nam Định", shortName: "Giao Châu" },
  { name: "Giao Hà, Giao Thủy, Nam Định", shortName: "Giao Hà" },
  { name: "Giao Hải, Giao Thủy, Nam Định", shortName: "Giao Hải" },
  { name: "Giao Hương, Giao Thủy, Nam Định", shortName: "Giao Hương" },
  { name: "Giao Lạc, Giao Thủy, Nam Định", shortName: "Giao Lạc" },
  { name: "Giao Long, Giao Thủy, Nam Định", shortName: "Giao Long" },
  { name: "Giao Nhân, Giao Thủy, Nam Định", shortName: "Giao Nhân" },
  { name: "Giao Phong, Giao Thủy, Nam Định", shortName: "Giao Phong" },
  { name: "Giao Tân, Giao Thủy, Nam Định", shortName: "Giao Tân" },
  { name: "Giao Thanh, Giao Thủy, Nam Định", shortName: "Giao Thanh" },
  { name: "Giao Thiện, Giao Thủy, Nam Định", shortName: "Giao Thiện" },
  { name: "Giao Thịnh, Giao Thủy, Nam Định", shortName: "Giao Thịnh" },
  { name: "Giao Tiến, Giao Thủy, Nam Định", shortName: "Giao Tiến" },
  { name: "Giao Xuân, Giao Thủy, Nam Định", shortName: "Giao Xuân" },
  { name: "Giao Yến, Giao Thủy, Nam Định", shortName: "Giao Yến" },
  { name: "Hồng Thuận, Giao Thủy, Nam Định", shortName: "Hồng Thuận" },
  { name: "Bạch Long, Giao Thủy, Nam Định", shortName: "Bạch Long" },
  { name: "Bình Hòa, Giao Thủy, Nam Định", shortName: "Bình Hòa" },
  { name: "Vĩnh Quang, Giao Thủy, Nam Định", shortName: "Vĩnh Quang" }
];
